live_config_reload = true

[bell]
animation = "EaseOutExpo"

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#eceff4"
text = "#282828"

[colors.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#2e3440"
foreground = "#d8dee9"

[colors.selection]
background = "#eceff4"
text = "#4c566a"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 13

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 1

[shell]
program = "/usr/local/bin/fish"

[window]
decorations = "transparent"
dynamic_padding = true
dynamic_title = true

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 4
y = 22

[window.position]
x = 50
y = 85
