#!/usr/bin/env bash

set -x

# ====== Variables =============================

declare -A gaps
declare -A color

gaps["top"]="4"
gaps["bottom"]="4"
gaps["left"]="4"
gaps["right"]="4"
gaps["inner"]="4"

color["focused"]="0xE0808080"
color["normal"]="0x00010101"
color["preselect"]="0xE02d74da"

# Uncomment to refresh ubersicht widget on workspace change
# Make sure to replace WIDGET NAME for the name of the ubersicht widget
#ubersicht_spaces_refresh_command="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"WIDGET NAME\"'"

# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ===== Tiling setting =========================

yabai -m config layout bsp

yabai -m config top_padding "${gaps["top"]}"
yabai -m config bottom_padding "${gaps["bottom"]}"
yabai -m config left_padding "${gaps["left"]}"
yabai -m config right_padding "${gaps["right"]}"
yabai -m config window_gap "${gaps["inner"]}"

yabai -m config mouse_follows_focus autofocus
yabai -m config focus_follows_mouse on

yabai -m config window_topmost off
yabai -m config window_opacity off
yabai -m config window_shadow float

yabai -m config window_border on
yabai -m config window_border_width 2
yabai -m config active_window_border_color "${color["focused"]}"
yabai -m config normal_window_border_color "${color["normal"]}"
yabai -m config insert_feedback_color "${color["preselect"]}"

yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90
yabai -m config split_ratio 0.50

yabai -m config auto_balance on

yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# ===== Rules ==================================

yabai -m rule --add label="飞书" app="^飞书$" manage=off
yabai -m rule --add label="Lark" app="^Lark$" manage=off
yabai -m rule --add label="Feishu" app="^Feishu$" manage=off
yabai -m rule --add label="微信" app="^微信$" manage=off
yabai -m rule --add label="Wechat" app="^微信$" title="^(朋友圈|相册)$" manage=off
yabai -m rule --add label="QQ" app="^QQ$" title="QQ" manage=off
yabai -m rule --add app="WhatsApp" manage=off
yabai -m rule --add app="^Telegram$" manage=off
yabai -m rule --add app="Discord" manage=off
yabai -m rule --add label="Zotero" app="^Zotero$" manage=off
yabai -m rule --add label="input source pro" app="^Input Source Pro$" manage=off

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="^.*Calendar.*$" manage=off
yabai -m rule --add label="^.*Calendar.*$" manage=off
yabai -m rule --add title="^.*Calendar.*$" manage=off
yabai -m rule --add app="^.*FaceTime.*$" manage=off
yabai -m rule --add label="系统设置" app="^系统设置$" manage=off
yabai -m rule --add label="关于本机" app="系统信息" manage=off
yabai -m rule --add app="^活动监视器$" manage=off
yabai -m rule --add app="^信息$" manage=off
yabai -m rule --add app="^字体册$" manage=off
yabai -m rule --add app="^计算器$" manage=off
yabai -m rule --add app="^词典$" manage=off
yabai -m rule --add app="日历" manage=off
yabai -m rule --add app="^时钟$" manage=off
yabai -m rule --add label="Safari浏览器" app="^Safari浏览器$" title="^(通用|标签页|密码|搜索|安全性|隐私|网站|扩展|高级)$" manage=off
yabai -m rule --add label="邮件" app="^邮件$" manage=off
yabai -m rule --add label="访达" app="^访达$" title="^(简介|访达设置|下载|复制|拷贝|共享|连接|移动|前往文件夹|废纸篓)$" manage=off
yabai -m rule --add label="系统信息" app="系统信息" title="MacBook Pro" manage=off
yabai -m rule --add app="^音乐$" manage=off
yabai -m rule --add label="系统信息" app="System Information" manage=off
yabai -m rule --add label="软件更新" title="软件更新" manage=off
yabai -m rule --add label="天气" app="^天气$" manage=off
yabai -m rule --add app="^照片$" manage=off
yabai -m rule --add app="^播客$" manage=off

yabai -m rule --add app="^网易云音乐$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Quicktime Player$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add app="^Elmedia Player$" manage=off
yabai -m rule --add app="^.*Affinity.*$" manage=off
yabai -m rule --add app="^Final Cut Pro$" manage=off
yabai -m rule --add app="^ArcTime Pro$" manage=off
yabai -m rule --add app="^.*iMovie.*$" manage=off
yabai -m rule --add app="^Logic Pro$" manage=off
yabai -m rule --add app="^MainStage$" manage=off
yabai -m rule --add app="^DaVinci Resolve$" manage=off
yabai -m rule --add app="^Motion$" manage=off
yabai -m rule --add app="^Compressor$" manage=off
yabai -m rule --add app="^.*Luminar.*$" manage=off

yabai -m rule --add label="App Cleaner & Uninstaller" app="^App Cleaner & Uninstaller$" manage=off
yabai -m rule --add label="AppCleaner" app="^AppCleaner$" manage=off
yabai -m rule --add label="KeyCastr" app="^KeyCastr$" eymanage=off
yabai -m rule --add app="^.*Bartender.*$" manage=off
yabai -m rule --add app="^.*Ice.*$" manage=off
yabai -m rule --add app="^.*Thaw.*$" manage=off
yabai -m rule --add app="^.*Pixelmator.*$" manage=off
yabai -m rule --add app="^.*Downie.*$" manage=off
yabai -m rule --add app="^Pictogram$" manage=off
yabai -m rule --add label="Foldor" app="^Foldor$" manage=off
yabai -m rule --add app="^.*Alfred.*$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^.*HP.*$" manage=off
yabai -m rule --add app="^.*1Password.*$" manage=off
yabai -m rule --add app="^.*Mos.*$" manage=off
yabai -m rule --add app="^.*AltTab.*$" manage=off
yabai -m rule --add app="^.*DockDoor.*$" manage=off
yabai -m rule --add app="^.*pot.*$" manage=off

yabai -m rule --add app="^Happy Hacking Keyboard Keymap Tool$" manage=off
yabai -m rule --add app="^CLion$" manage=off
yabai -m rule --add app="^RustRover.*$" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" manage=off
yabai -m rule --add app="^GoLand$" manage=off
yabai -m rule --add app="^PyCharm$" manage=off
yabai -m rule --add app="(?i).*neovide.*" manage=off
yabai -m rule --add app="Neovide" manage=off
yabai -m rule --add label="Typora" app="^Typora$" title="偏好设置" manage=off
yabai -m rule --add app="^UPDF$" manage=off
yabai -m rule --add app="^.*Craft.*$" manage=off
yabai -m rule --add app="^.*Microsoft.*$" manage=off
yabai -m rule --add app="^Postman$" manage=off
yabai -m rule --add app="^.*Clash.*$" manage=off
yabai -m rule --add app="^.*V2ray.*$" manage=off

yabai -m rule --add app="^.*Office.*$" manage=off

yabai -m rule --add app="^.*League.*$" manage=off
yabai -m rule --add app="^.*Riot.*$" manage=off

# ===== Signals ================================

yabai -m signal --add event=application_front_switched action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=display_changed action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=space_changed action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=window_created action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=window_destroyed action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=window_focused action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=window_title_changed action="${ubersicht_spaces_refresh_command}"

set +x
printf "yabai: configuration loaded...\\n"
